name: Lint and build docker image

on: push

jobs:
  lint-and-build:
    name: Lint and build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run super linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .github/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.PAT_GITHUB_ACTIONS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            REQLESS_UI_GIT_REF=${{ github.sha }}
            REQLESS_UI_VERSION=0.0.0
          cache-from: mode=max,type=gha
          cache-to: type=gha
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          tags: |
            tdg5/reqless-ui:${{ github.sha }}
            tdg5/reqless-ui:latest
